version: '3'
services:
  openbastion:
    image: openbastion:latest
    container_name: openbastion
    ports:
      - "80:80"
      - "2100:2100"
    networks:
      - public
      - private
    volumes:
      #- "/var/log:/var/log"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: always
networks:
  public:
    driver: bridge
  private:
    driver: bridge
